### ISSUE TITLE
question about the very large genome 

### ISSUE THREAD

**Issue by longzhangnation** [lbcb-sci/raven#20]
Hello, After reading your paper , I am curious about if it is useful for my genome . So I have some questions . I have a very large genome ,about 6 Gb , to be sequenced  . Will the software support its assembling? How about the heterozygosity dealing when it assembles the high heterozygosity  speceies to 2.0% ?  And how about the run time and RAM consuming compared to WTDBG2 ? Thank you  in advance .

**Comment by rvaser** [comment]
Hello,
Raven should work fine on higher heterozygosity percentages. I cannot tell you the expected run time, but the memory consumption is less than `1.3 * sizeof(Fastq)`. Both are affected with the sequencing depth. Regarding the comparison with Wtdbg2, we are redoing our benchmark due to recent improvements of Raven. Once completed, I can link it here.

Best regards,
Robert

**Comment by longzhangnation** [comment]
Thank you  . Will very large genome assembling be supported ? I want to test it . As you know ,during the assembling , many softwares may generate very big files consuming large roon of disk . Will Ra avoid the situation ?

**Comment by rvaser** [comment]
Raven only generates one file which is overwritten after each step in the assembly. It is used to resume the assembly if something breaks or the user wants to change the number of polishing rounds. The size of the file is usually two times smaller than the Fastq file.

**Comment by longzhangnation** [comment]
Thank you . got it . Have a nice day .
