### ISSUE TITLE
raven_build_tests

### ISSUE THREAD

**Issue by erinyoung** [lbcb-sci/raven#46]
My problem is due to my lack of skill. I'm hoping for a command that I copy and paste into my terminal.

This is the command to install raven:
```
git clone https://github.com/lbcb-sci/raven && cd raven && mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release .. && make
```

Which works great. No issues here.

I want to try the 'raven_build_tests' when I build raven.

Where exactly does this happen?

If I wanted to try building with GPU, what is the installation instructions for that?

**Comment by rvaser** [comment]
Hi,
option `raven_build_tests` is on by default, and will create `raven_test` inside `build/bin`. You can turn it off with:
```bash
cmake -DCMAKE_BUILD_TYPE=Release -Draven_build_tests=OFF .. && make
```
If you want GPU support, run the following:
```bash
cmake -DCMAKE_BUILD_TYPE=Release -Dracon_enable_cuda=ON .. && make
```
It will enable additional options when `raven -h` is run, which you need to set for polishing on the GPU (otherwise polishing will be done on CPU).

Best regards,
Robert

**Comment by erinyoung** [comment]
Thank you! That was what I was looking for!
